### ISSUE TITLE
Support Unicode and slow connection problem

### ISSUE THREAD

**Issue by bluesimke** [Subtixx/source-rcon-library#1]
Dear developer :

  First of all, thank you for such a good job !

  But i found it seems like a pity about Encoding & Stability :
  1.Unicode character can't be support when server writing/reading a packet.
  2.Under a stressful test, the Client could failed to send a command to Server SILENTLY. (example : sending 4 commands/s lasting for about 5 min )

  I don't know so much about C#, i admire this project just because i'm a ARK player and want to do something about automatic server management .

**Comment by Subtixx** [comment]
Hello, thanks for contributing to this project.

Unicode characters can't be sent, since the specification of the 'Valve source RCON protocol' is not supporting it. As you can see in this picture:
![](https://i.imgur.com/RHXQjmx.png)
The body (or payload) is a Null-terminated ASCII string.

I don't understand what you mean by:
> the Client could failed to send a command to Server SILENTLY

Could you be a little bit more specific?

**Comment by bluesimke** [comment]
I'm so sorry, my first language is not English, so what i describe in last reply may confuse you.
Simply, if you try to send 4 command per second to a server and continue doing that last about 5-10 mins, then the client could failed to send anything actually, but no obviously tips in the console when the sending action not work. no return value in the code for reconnecting as well.
And about the Unicode support, it's right that Valve source RCON didn't support at all, but for many games such as ARK, we have server api plugins to make it possible, and if this project could provide Unicode support it would be great and much more friendly to non-English users.
Thank you all the same !

**Comment by bluesimke** [comment]
I try to make the unicode work by modify coding but it failed again and again - -
C# is too familiar and difficult for me.
I use a class write by PHP before, but i work no perfect as this one.

**Comment by Subtixx** [comment]
Didn't know about the ARK part. I'll look into it.

The other part with the "slow" connection I'll first have to re-produce.

**Comment by bluesimke** [comment]
The Unicode part is not very important for this project, because it's not a common demand, but we may need to pay high attention to the other problem.
I think we need a return value or signal when command sending failed so that we could try to make a reconnection.
Thank you !

**Comment by Subtixx** [comment]
This should be fixed. If not please open a new issue.
